# Generated by Django 4.2.1 on 2023-05-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicadas',
            field=models.BooleanField(default=False),
        ),
    ]
